# This is a basic workflow to help you get started with Actions

name: Build and deploy site

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the react-web branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          py7zrversion: '>=0.20.2'
          version: '6.5.0'
          host: 'linux'
          target: 'desktop'
          arch: 'wasm_multithread'
          modules: 'qtcharts qtdatavis3d qtgrpc qthttpserver qtimageformats qtlottie qtmultimedia qtquick3dphysics qtscxml qtspeech qtvirtualkeyboard qtwebchannel qtwebsockets qt5compat qtquick3d qtquicktimeline qtshadertools'
      - name: Configure and Build
        runs: |
          mkdir build
          cd build
          qmake ../aircs-map-qt.pro
          make
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/master'
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   permissions:
  #     pages: write
  #     id-token: write
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
