# This is a basic workflow to help you get started with Actions

name: Build and deploy site

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the react-web branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - uses: actions/setup-node@v3
        name: Set up node.js
        with:
          node-version: 16
      - name: Acquire latest station information
        run: |
          node generate-json.js
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 1.39.8
          actions-cache-folder: 'emsdk-cache'
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          py7zrversion: '>=0.20.2'
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'wasm_32'
          modules: 'qtcharts qtdatavis3d qtlottie qtnetworkauth qtpurchasing qtquicktimeline qtscript qtvirtualkeyboard qtwebglplugin'
          cache: true
      - name: Configure
        run: |
          mkdir build
          cd build
          qmake ../aircs-map-qt.pro
      - name: Build
        run: |
          cd build
          make
      - name: Clean
        run: |
          cd build
          rm *.cpp *.h *.o Makefile
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
